name       : python-pathlib2
version    : 2.3.5
release    : 2
source     :
    - https://github.com/mcmtroffaes/pathlib2/archive/2.3.5.tar.gz : 4b57e7ec31a993d259e63bc1af505f7508cea1ad0c9b226fc2e5d1b06e06b016
license    : MIT
component  : programming.python
summary    : Fork of pathlib aiming to support the full stdlib Python API.
description: |
    Fork of pathlib aiming to support the full stdlib Python API.
builddeps  :
    - python-setuptools
rundeps    :
    - python-scandir
    - python-six
setup      : |
    %python_setup
install    : |
    %python_install
